# Generated by Django 3.2.7 on 2022-11-17 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sms',
            name='photo',
        ),
    ]
